=== Rodez-IUT/dut-info2-filmprovider-tommargalejo/Part1-XML-DTD/resources/XML3/Librairie.dtd
<!ELEMENT livre (titre, auteurs, description, prix)>
    <!ATTLIST livre ISBN CDATA #REQUIRED >

<!ELEMENT librairie (entete, livre+)>

<!-- contenu entête -->
<!ELEMENT strong (#PCDATA)>
<!ELEMENT em (#PCDATA)>
<!ELEMENT img EMPTY>
        <!ATTLIST img source CDATA #REQUIRED
                  title CDATA #IMPLIED
                >

<!ELEMENT titre (#PCDATA)>

<!-- contenu auteur -->

<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>


<!ENTITY % texteFormate "(#PCDATA | strong | em | img)*">
<!ENTITY % identite "(nom, prenom?)">

<!ELEMENT auteur %identite;>
<!ELEMENT entete %texteFormate;>

<!ELEMENT direction %identite;>
<!ELEMENT membres (#PCDATA)>

<!ELEMENT collectif (direction, membres) >

<!ELEMENT auteurs (auteur+ | collectif)>

<!ELEMENT description %texteFormate;>

<!ELEMENT prix (#PCDATA)>
    <!ATTLIST prix
                   devise (euro | livre | dollar) "euro"
                   type (HT | TTC) "HT"
                   tva NMTOKEN #FIXED "5.5"
    >

<!ENTITY copyright "©Librairie &amp; Internet 2020 ">

=== Rodez-IUT/dut-info2-filmprovider-tommargalejo/Part1-XML-DTD/resources/XML3/Librairie.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE librairie SYSTEM "Librairie.dtd">
<librairie>
    <entete>Le centre de documentation de <em>l'IUT de rodez</em>. &copyright;</entete>
    <livre ISBN="TSJ01">
        <titre>Tout sur le java</titre>
        <auteurs>
            <auteur>
                <nom>
                    Delanoy
                </nom>
            </auteur>
            <auteur>
                <nom>
                    John Doe
                </nom>
            </auteur>
        </auteurs>
        <description>Les bases de la programmation en <strong>Java</strong></description>
        <prix devise="euro" tva="5.5" type="TTC">45</prix>
    </livre>
    <livre ISBN="test">
        <titre>Bassiste magazine</titre>
        <auteurs>
            <collectif>
                <direction>
                    <nom>Auteur 1</nom>
                    <prenom>renom de l'auteur</prenom>
                </direction>
                <membres>...</membres>
            </collectif>
        </auteurs>
        <description>Les bases de la programmation en <strong>Java</strong></description>
        <prix devise="euro" tva="5.5" type="TTC">35</prix>
    </livre>
</librairie>
