=== Rodez-IUT/dut-info2-filmprovider-tommargalejo/Part2-XSLT-XSD/XSD7/FilmProvier.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://formationxml/filmprovider"
           xmlns:fox="http://formationxml/filmprovider"
           elementFormDefault="qualified"
>

<!--Films-->
    <xs:element name="films">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="fox:realisateur" maxOccurs="unbounded"/>
                <xs:element ref="fox:film" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

<!--RÃ©alisateur-->
    <xs:element name="realisateur">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="prenom" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="nom" type="xs:string" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="id_realisateur" use="required" type="fox:real_"/>
        </xs:complexType>
        <xs:key name="pkReal">
            <xs:selector xpath="realisateur"></xs:selector>
            <xs:field xpath="@id_realisateur"></xs:field>
        </xs:key>
    </xs:element>

<!--Film-->
    <xs:element name="film">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="titre" type="xs:string"/>

                <!--Resume-->
                <xs:element name="resume">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="image" minOccurs="0">
                                <xs:complexType>
                                    <xs:attribute name="source" type="xs:anyURI"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="text" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id_film" type="fox:film_" use="required"/>
            <xs:attribute name="id_realisateur" type="fox:real_" use="required"/>
            <xs:attribute name="annee" type="fox:dateFilm_" use="required"/>
        </xs:complexType>
        <xs:key name="pkFilm">
            <xs:selector xpath="film"></xs:selector>
            <xs:field xpath="@id_film"></xs:field>
        </xs:key>
        <xs:keyref refer="pkReal" name="fkRealFilm">
            <xs:selector xpath="film"/>
            <xs:field xpath="@id_realisateur"/>
        </xs:keyref>
    </xs:element>


    <xs:simpleType name="film_">
        <xs:restriction base="xs:string">
            <xs:pattern value="film_\d{2}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="real_">
        <xs:restriction base="xs:string">
            <xs:pattern value="real_\d{2}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="dateFilm_"> <xs:restriction base="xs:integer">
        <xs:minInclusive value="1920"/>
            <xs:maxInclusive value="2006"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== Rodez-IUT/dut-info2-filmprovider-tommargalejo/Part2-XSLT-XSD/XSD7/FilmProvider1.xml
<?xml version="1.0" encoding="UTF-8"?>

<fox:films
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="FilmProvier.xsd"
        xmlns:fox="http://formationxml/filmprovider">

    <fox:realisateur id_realisateur="real_01">
        <fox:prenom>Tanguy</fox:prenom>
        <fox:nom>Fenouillot</fox:nom>
    </fox:realisateur>
    <fox:realisateur id_realisateur="real_02">
        <fox:prenom>Florian</fox:prenom>
        <fox:nom>Hyver</fox:nom>
    </fox:realisateur>

    <fox:film id_film="film_01" id_realisateur="real_01" annee="2001">
        <fox:titre>Film 1</fox:titre>
        <fox:resume>
            <fox:text>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam, architecto aut consequatur culpa dolorem earum et fugiat harum id iure, molestiae molestias numquam? Culpa deserunt dolor maiores natus reprehenderit saepe.</fox:text>
        </fox:resume>
    </fox:film>
    <fox:film id_film="film_02" id_realisateur="real_02" annee="2003">
        <fox:titre>Film 2</fox:titre>
        <fox:resume>
            <fox:image source="killbill.jpg"/>
            <fox:text>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto, culpa delectus dignissimos doloremque, doloribus enim eos fugit ipsam itaque laborum maiores natus nihil pariatur quae sint sunt, temporibus voluptate voluptatum?</fox:text>
        </fox:resume>
    </fox:film>

</fox:films>

=== Rodez-IUT/dut-info2-filmprovider-tommargalejo/Part2-XSLT-XSD/XSD7/FilmProvider.xml
<?xml version="1.0" encoding="UTF-8"?>

<fox:films
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="FilmProvier.xsd"
    xmlns:fox="http://formationxml/filmprovider">
    <fox:realisateur id_realisateur="real_01">
        <fox:prenom>Martin</fox:prenom>
        <fox:nom>Scorsese</fox:nom>
    </fox:realisateur>
    <fox:realisateur id_realisateur="real_02">
        <fox:prenom>Quentin</fox:prenom>
        <fox:nom>Tarantino</fox:nom>
    </fox:realisateur>
    <fox:realisateur id_realisateur="real_03">
        <fox:prenom>Steven</fox:prenom>
        <fox:nom>Spielberg</fox:nom>
    </fox:realisateur>
    <fox:film id_film="film_01" id_realisateur="real_03" annee="2001">
        <fox:titre>Minority Report</fox:titre>
        <fox:resume>
            <fox:text>Un homme est victime d'une machination. Il est pris au piège d'un système qu'il a l'habitude de controler.</fox:text>
        </fox:resume>
    </fox:film>
    <fox:film id_film="film_02" id_realisateur="real_02" annee="2003">
        <fox:titre>Kill Bill</fox:titre>
        <fox:resume>
            <fox:image source="killbill.jpg"/>
            <fox:text>Une femme se venge des personnes qui ont voulu l'assassiner.</fox:text>
        </fox:resume>
    </fox:film>
    <fox:film id_film="film_03" id_realisateur="real_01" annee="1995">
        <fox:titre>Casino</fox:titre>
        <fox:resume>
            <fox:image source="deniro.jpg"/>
            <fox:text>Le monde de la mafia italienne mêlée à celui des casinos...</fox:text>
        </fox:resume>
    </fox:film>

    <fox:film id_film="film_04" id_realisateur="real_01" annee="1990">
        <fox:titre>Les affranchis</fox:titre>
        <fox:resume>
            <fox:text>Inspiré d'un fait réel : histoire de mafia italienne.</fox:text>
        </fox:resume>
    </fox:film>
</fox:films>
